# Generated by Django 4.1.7 on 2023-10-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='biography',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
