# Generated by Django 4.1.7 on 2023-11-30 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborationnetwork',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collaborationnetwork',
            name='orchestrator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orchestrator', to=settings.AUTH_USER_MODEL),
        ),
    ]
