# Generated by Django 4.1.7 on 2023-05-04 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Survey",
        ),
    ]
