# Generated by Django 4.1.7 on 2023-12-04 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
        ('djf_surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='survey',
            name='collaboration_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network', to='organization.collaborationnetwork', verbose_name='Collaboration Network'),
        ),
        migrations.AddField(
            model_name='subdimension',
            name='dimension',
            field=models.ManyToManyField(related_name='sub_dimensions', to='djf_surveys.dimension'),
        ),
        migrations.AddField(
            model_name='question',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='djf_surveys.dimension'),
        ),
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='djf_surveys.level'),
        ),
        migrations.AddField(
            model_name='question',
            name='subdimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='djf_surveys.subdimension'),
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='djf_surveys.survey', verbose_name='survey'),
        ),
        migrations.AddField(
            model_name='dimension',
            name='level',
            field=models.ManyToManyField(related_name='dimensions', to='djf_surveys.level'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='djf_surveys.question', verbose_name='question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djf_surveys.useranswer', verbose_name='user answer'),
        ),
    ]
