# Generated by Django 4.1.7 on 2024-03-09 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djf_surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='edit_field',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='djf_surveys.editfield'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='edit_field',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='editfield', to='djf_surveys.editfield'),
        ),
    ]
