# Generated by Django 4.1.7 on 2024-02-17 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djf_surveys', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditField',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('Dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension', to='djf_surveys.dimension')),
                ('Level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level', to='djf_surveys.level')),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='djf_surveys.question')),
                ('SubDimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdimension', to='djf_surveys.subdimension')),
                ('Survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='djf_surveys.survey')),
            ],
        ),
    ]
