# Generated by Django 4.1.7 on 2024-03-15 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djf_surveys', '0003_remove_survey_edit_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='edit_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='djf_surveys.editfield'),
        ),
    ]
