# Generated by Django 4.1.7 on 2023-06-09 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djf_surveys', '0003_remove_survey_org_profiles_survey_org_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='org_type',
            field=models.CharField(max_length=200, verbose_name='Organization type'),
        ),
    ]
