# Generated by Django 4.1.7 on 2024-03-15 07:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('djf_surveys', '0004_alter_question_edit_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editfield',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
