# Generated by Django 4.1.7 on 2023-06-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djf_surveys', '0004_alter_survey_org_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='org_type',
            field=models.CharField(blank=True, max_length=200, verbose_name='Organization type'),
        ),
    ]
