# Generated by Django 4.1.7 on 2023-05-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
        ('djf_surveys', '0011_alter_question_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='org_profiles',
            field=models.ManyToManyField(blank=True, to='organization.orgprofile'),
        ),
    ]
