# Generated by Django 4.1.7 on 2023-05-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
        ('djf_surveys', '0012_survey_org_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='org_profiles',
            field=models.ManyToManyField(blank=True, help_text='Select Organizations that are allowed to take the survey', to='organization.orgprofile'),
        ),
    ]
