# Generated by Django 4.1.7 on 2023-05-18 09:30

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_order', models.IntegerField(blank=True, null=True, unique=True)),
                ('question_text', models.CharField(blank=True, max_length=2000, null=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('question_type', models.CharField(choices=[('checkbox', 'Multiple Choice'), ('radio', 'Single Choice'), ('range', 'Slider')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_]*$', 'Only letters, numbers, and underscores are allowed.')])),
                ('survey_name_slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('description', models.CharField(max_length=8000)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('survey_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('finished', 'Finished'), ('unstarted', 'Unstarted')], default='unstarted', max_length=10)),
            ],
        ),
    ]
