# Generated by Django 4.1.7 on 2023-05-07 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('respondent_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Respondent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(blank=True, max_length=6000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_order', models.IntegerField(blank=True, null=True)),
                ('question_text', models.CharField(blank=True, max_length=2000, null=True)),
                ('is_mandatory', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('question_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyStatus',
            fields=[
                ('survey_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('survey_status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('survey_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=8000)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('min_responses', models.IntegerField(blank=True, null=True)),
                ('max_responses', models.IntegerField(blank=True, null=True)),
                ('survey_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Survey.surveystatus')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('begin_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Survey.respondent')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Survey.survey')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('question_option_id', models.AutoField(primary_key=True, serialize=False)),
                ('qo_order', models.IntegerField(blank=True, db_column='QO_order', null=True)),
                ('qo_value', models.CharField(blank=True, db_column='QO_value', max_length=100, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Survey.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Survey.questiontype'),
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('answer_option_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Survey.answer')),
                ('question_option', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Survey.questionoption')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Survey.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Survey.response'),
        ),
    ]
