# Generated by Django 4.1.7 on 2023-05-14 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('Survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='org_profiles',
            field=models.ManyToManyField(blank=True, to='organization.orgprofile'),
        ),
        migrations.AddField(
            model_name='response',
            name='respondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Survey.respondent'),
        ),
        migrations.AddField(
            model_name='response',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Survey.survey'),
        ),
        migrations.AddField(
            model_name='respondent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.orgprofile'),
        ),
    ]
