# Generated by Django 4.1.7 on 2023-05-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_order',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('checkbox', 'Multiple Choice'), ('radio', 'Single Choice'), ('range', 'Slider')], max_length=10),
        ),
    ]
